version: '3.8'

services:
  postgres:
    container_name: vacancies-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DATABASE: vacancies
      PGDATA: /data/postgres
    volumes:
      - ./data/postgres:/data/postgres
